// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Works with Firebase Emulators too (configure emulators in main.dart)
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          're-run FlutterFire CLI to configure.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRIxyRi2wnFcUh3oE4c3vUeU_Wt4tLTG4',
    appId: '1:453264832141:web:b57aef92e9213f5dc1d4c4',
    messagingSenderId: '453264832141',
    projectId: 'chatapp-62eff',
    authDomain: 'chatapp-62eff.firebaseapp.com',
    storageBucket: 'chatapp-62eff.firebasestorage.app',
    measurementId: 'G-Z0S9KGTJFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqBQDWVt9hItwyv682Qo_gNu48qrSaEH8',
    appId: '1:453264832141:android:77b44e1a1251287fc1d4c4',
    messagingSenderId: '453264832141',
    projectId: 'chatapp-62eff',
    storageBucket: 'chatapp-62eff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpOAeKWJVFnx31ZdV1E64eOt4Fq_RdsUU',
    appId: '1:453264832141:ios:7e922d8692229c1ec1d4c4',
    messagingSenderId: '453264832141',
    projectId: 'chatapp-62eff',
    storageBucket: 'chatapp-62eff.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpOAeKWJVFnx31ZdV1E64eOt4Fq_RdsUU',
    appId: '1:453264832141:ios:7e922d8692229c1ec1d4c4',
    messagingSenderId: '453264832141',
    projectId: 'chatapp-62eff',
    storageBucket: 'chatapp-62eff.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRIxyRi2wnFcUh3oE4c3vUeU_Wt4tLTG4',
    appId: '1:453264832141:web:cbdaaa2d4b602c89c1d4c4',
    messagingSenderId: '453264832141',
    projectId: 'chatapp-62eff',
    authDomain: 'chatapp-62eff.firebaseapp.com',
    storageBucket: 'chatapp-62eff.firebasestorage.app',
    measurementId: 'G-EDXK67NV9F',
  );
}
